name: Build and Push Docker Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image from master branch
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/starbuggx/docker-unifi:latest

      - name: Build and push Docker image from other branches
        if: github.ref_name != 'master'
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/starbuggx/docker-unifi:${{ github.ref_name }}
          
